# Generated by Django 4.1.5 on 2023-02-09 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_code',
            field=models.CharField(default=None, max_length=50, verbose_name='Staff ID'),
            preserve_default=False,
        ),
    ]
