# Generated by Django 4.1.5 on 2023-02-11 10:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, verbose_name='Branch Code')),
                ('name', models.CharField(max_length=50, verbose_name='Branch Name')),
                ('address', models.TextField(verbose_name='Address')),
                ('phone_number', models.CharField(max_length=50, verbose_name='Phone Number')),
                ('email_address', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('fax', models.CharField(max_length=50, verbose_name='Fax')),
                ('logo', models.ImageField(upload_to='photos/branches/%Y/%m/%d', verbose_name='Branch Logo')),
                ('slogan', models.CharField(blank=True, max_length=50, null=True, verbose_name='Slogan')),
                ('mantra', models.CharField(blank=True, max_length=50, null=True, verbose_name='Mantra')),
                ('nickname', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nickname')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Branch',
                'verbose_name_plural': 'Branches',
                'db_table': 'branch',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_code', models.CharField(max_length=50, verbose_name='Phone Code')),
                ('zip_code', models.CharField(max_length=50, verbose_name='Zip Code')),
                ('country_name', models.CharField(max_length=50, verbose_name='Country Name')),
                ('abbreviation', models.CharField(max_length=50, verbose_name='Abbreviation')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, verbose_name='Region Code')),
                ('name', models.CharField(max_length=50, verbose_name='Region Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Region',
                'verbose_name_plural': 'Regions',
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, verbose_name='School Code')),
                ('name', models.CharField(max_length=50, verbose_name='School Name')),
                ('address', models.TextField(verbose_name='Address')),
                ('phone_number', models.CharField(max_length=50, verbose_name='Phone Number')),
                ('email_address', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('fax', models.CharField(max_length=50, verbose_name='Fax')),
                ('logo', models.ImageField(upload_to='photos/schools/%Y/%m/%d', verbose_name='School Logo')),
                ('slogan', models.CharField(blank=True, max_length=50, null=True, verbose_name='Slogan')),
                ('mantra', models.CharField(blank=True, max_length=50, null=True, verbose_name='Mantra')),
                ('nickname', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nickname')),
                ('date_of_establishment', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date of Establishment')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'School',
                'verbose_name_plural': 'Schools',
                'db_table': 'school',
            },
        ),
        migrations.CreateModel(
            name='ValidityStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Validity Status',
                'verbose_name_plural': 'Validity Statuses',
            },
        ),
    ]
