# Generated by Django 4.1.5 on 2023-02-10 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='country',
            old_name='name',
            new_name='country_name',
        ),
    ]
